### ISSUE TITLE
Typo3 11.5.9: Blocking ext_localconf.php of other extension(s)

### ISSUE THREAD

**Issue by floriankuehl** [AOEpeople/felogin_bruteforce_protection#26] opened 2022-06-29 11:50 UTC
After activating this extension, Typo3 shows error messages that a plugin of my custom extension (secured behind felogin) does not know any actions that are provided in the ext_localconf.php. File is present, but not loaded. 
After deactivating the the bruteforce extension, everything works fine again. Why is that?
I installed another authentication service for login via email and programmatic login. Maybe it is interferring?

**Comment by cyberp** [comment] 2022-09-07 14:32
I have the same problem.
I used this extension with Typo3 V9 and everything was fine.
After upgrade to Typo3 V11 and extensions version 10.0.0 after the activation of the extension Typo3 shows an error message that the default controller of one plugin in one of my own extension cant be found.

**Comment by TomSchenk** [comment] 2023-06-30 07:46
Hi,
sorry for that - is this still relevant?
Can you please provide more information (log entries) on this?
Unfortunately, we are not able to reproduce this error in our setups.

**Comment by tlayh** [comment] 2023-07-28 11:14
Closing since this is one year old and we did not get any feedback.

**Closed by tlayh** 2023-07-28 11:14 UTC
