### ISSUE TITLE
TYPO3 9.5 LTS compatibility

### ISSUE THREAD

**Issue by typo3ua** [AOEpeople/felogin_bruteforce_protection#17] opened 2018-12-26 10:15 UTC
Now that a TYPO3 v. 9.5 with long term support is released it would be excellent to reassure compatibility with this version.

**Comment by tomasnorre** [comment] 2019-01-02 10:06
@typo3ua Please check https://github.com/AOEpeople/felogin_bruteforce_protection/tree/TYPO3v9

**Comment by typo3ua** [comment] 2019-01-02 10:40
This Version 2.0.0 available only on GIT?

**Comment by typo3ua** [comment] 2019-01-02 10:59
I tried to install `felogin_bruteforce_protection` - version `2.0.0` from here but I failed because I get message `Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 7.6.0 - 7.6.99`

**Comment by typo3ua** [comment] 2019-01-02 11:17
I was could to get and install need version via download .zip but I see old number of version `'version' => '1.6.0',`

**Comment by typo3ua** [comment] 2019-01-02 11:44
I did login failures more than 3 times, but did get no message about it... nothing happens. What is I do wrong?

My config:

![fe_prot_1](https://user-images.githubusercontent.com/638022/50590617-69884e00-0e94-11e9-9893-ef4cf0671429.png)

**Comment by tomasnorre** [comment] 2019-01-02 13:14
> This Version 2.0.0 available only on GIT?

Yes, it's currently not release over packagist or TER. 

> I did login failures more than 3 times, but I did get no message about it... nothing happens. What is I do wrong?

I cannot tell from the top of my head, would need to look into it. 

Regarding the version number I'll have to check if i did something wrong in the version constraints.

**Comment by tomasnorre** [comment] 2019-01-02 14:20
Will try to reproduce with the steps you described.

But cannot say when I'll get to this. Will not be today that's for sure.

**Comment by tomasnorre** [comment] 2019-01-03 17:22
@typo3ua 

> I tried to install `felogin_bruteforce_protection` - version `2.0.0` [from here](https://github.com/AOEpeople/felogin_bruteforce_protection/tree/TYPO3v9) but I failed because I get message `Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 7.6.0 - 7.6.99`

This is because the 2.0.0 is not supporting TYPO3V9, there are some changes in 2.0.0 that didn't get merged into TYPO3v9 yet. 

I still need to check your setup though and to test your problem.

**Comment by tomasnorre** [comment] 2019-07-25 10:13
@typo3ua 

The 2.1.0 release should support TYPO3 v9, unfortunately we made a mistake so the 2.1.0 release don't.

I'll figure out how to resolve this caos..

There are also a TYPO3V9 branch, that should be working.

**Closed by tomasnorre** 2019-07-25 10:13 UTC

**Comment by typo3ua** [comment] 2019-07-25 12:24
...it is nice news. Thank for your work.

**Comment by tomasnorre** [comment] 2019-07-25 13:46
You're welcome. Let me know if you're having any problems.
